# Generated by Django 5.0.2 on 2024-03-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('L', 'LARGE'), ('S', 'SMALL'), ('M', 'MEDIUM')], max_length=1)),
            ],
        ),
    ]
