# Generated by Django 5.0.2 on 2024-03-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic',
            new_name='pid',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'MEDIUM'), ('S', 'SMALL'), ('L', 'LARGE')], max_length=1),
        ),
    ]
