# Generated by Django 5.0.3 on 2024-03-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic',
            new_name='pid',
        ),
    ]
