# Generated by Django 5.0.2 on 2024-04-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=64)),
                ('usname', models.CharField(max_length=64)),
            ],
        ),
    ]
