# Generated by Django 5.0.3 on 2024-04-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=64)),
                ('uname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('pid', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('cid', models.CharField(max_length=4)),
                ('channel', models.PositiveIntegerField()),
            ],
        ),
    ]
